### ISSUE TITLE
Cannot debug unit tests with this plugin installed.

### ISSUE THREAD

**Issue by Athaphian** [jmhofer/eCobertura#1]
Hey, I like the plugin, but I cannot debug my unit tests. Is this known, am I doing something wrong? Or is this something that needs to be resolved?

Or in addition, a way to disable this plugin on certain projects would also solve this in a workaround way.. I couldn't find that option either.

**Comment by jmhofer** [comment]
I'll check what's going on there. - Normal debugging should not be affected by the plugin.

One idea: Maybe debugging works again after a clean build? - The plugin instruments the classes on the fly, and perhaps those classes are not debuggable while still intrumented from a previous Cobertura run.

**Comment by Athaphian** [comment]
Hey thanks for your quick response. I forgot to mention.. might be of interest. Im using groovy/grails and the particular testcase Im running is a grails unit test case, but coverage works just fine, so that shouldn't be any problem..

I had to uninstall the plugin for the moment, because I need to keep working and debugging is a must, but if you need some more info let me know.

**Comment by jmhofer** [comment]
You probably can debug anyway after running in covered mode if you do a "Project -> Clean..." before. This is due to the in-place instrumentation eCobertura is currently doing. Maybe you want to try this out and tell me whether it works for you?

Anyway, in-place instrumentation seems to be suboptimal for a lot of use cases, so I'm looking into alternatives.

**Comment by jmhofer** [comment]
Most probably fixed in 0.9.4 by avoiding in-place instrumentation.

**Comment by Athaphian** [comment]
Hey thanks, I will try out this new version.
